### ISSUE TITLE
need to be able to change the Border-bottom width

### ISSUE THREAD

**Issue by ghost** [javadbat/jb-time-input#1]
i need to change Border-bottom width

**Comment by javadbat** [comment]
thank you sir , we will add it soon

**Comment by javadbat** [comment]
sina this feature is already implimented and you can set it by css variable like this:

```css
jb-time-input{
  --jb-time-input-border-botton-width:1px
}

```
